---
- name: setup windows vms
  hosts: windows
  vars:
    ansible_shell_type: cmd
    ansible_user: ansible
  tasks:
  - name: test connection
    win_ping:
  - name: install choco
    win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  - name: install git for windows
    win_chocolatey:
      name: git.install
      state: latest
